/* Generated by Yosys 0.7 (git sha1 UNKNOWN, gcc 4.8.5 -fPIC -Os) */
`include "/research/ece/lnis/USERS/alacchi/Current_release/OpenFPGA/yosys/techlibs/common/simlib.v"
module s298_prevpr (G0, G1, G2, clk, G117, G132, G66, G118, G133, G67);
  input G0;
  input G1;
  (* init = 1'b0 *)
  reg G10;
  initial G10 = 1'b0;
  (* init = 1'b0 *)
  reg G11;
  initial G11 = 1'b0;
  output G117;
  output G118;
  (* init = 1'b0 *)
  reg G12;
  initial G12 = 1'b0;
  (* init = 1'b0 *)
  reg G13;
  initial G13 = 1'b0;
  output G132;
  output G133;
  (* init = 1'b0 *)
  reg G14;
  initial G14 = 1'b0;
  (* init = 1'b0 *)
  reg G15;
  initial G15 = 1'b0;
  (* init = 1'b0 *)
  reg G16;
  initial G16 = 1'b0;
  (* init = 1'b0 *)
  reg G17;
  initial G17 = 1'b0;
  (* init = 1'b0 *)
  reg G18;
  initial G18 = 1'b0;
  (* init = 1'b0 *)
  reg G19;
  initial G19 = 1'b0;
  input G2;
  (* init = 1'b0 *)
  reg G20;
  initial G20 = 1'b0;
  (* init = 1'b0 *)
  reg G21;
  initial G21 = 1'b0;
  (* init = 1'b0 *)
  reg G22;
  initial G22 = 1'b0;
  (* init = 1'b0 *)
  reg G23;
  initial G23 = 1'b0;
  output G66;
  output G67;
  input clk;
  wire n21;
  wire n26;
  wire n31;
  wire n36;
  wire n41;
  wire n46;
  wire n51;
  wire n56;
  wire n57;
  wire n59;
  wire n61;
  wire n64;
  wire n66;
  wire n66_1;
  wire n71;
  wire n76;
  wire n81;
  wire n86;
  always @(posedge clk)
      G10 <= n21;
  always @(posedge clk)
      G19 <= n66_1;
  always @(posedge clk)
      G20 <= n71;
  always @(posedge clk)
      G21 <= n76;
  always @(posedge clk)
      G22 <= n81;
  always @(posedge clk)
      G23 <= n86;
  always @(posedge clk)
      G11 <= n26;
  always @(posedge clk)
      G12 <= n31;
  always @(posedge clk)
      G13 <= n36;
  always @(posedge clk)
      G14 <= n41;
  always @(posedge clk)
      G15 <= n46;
  always @(posedge clk)
      G16 <= n51;
  always @(posedge clk)
      G17 <= n56;
  always @(posedge clk)
      G18 <= n61;
  \$lut  #(
    .LUT(4'b0001),
    .WIDTH(32'd2)
  ) _14_ (
    .A({ G10, G0 }),
    .Y(n21)
  );
  \$lut  #(
    .LUT(32'd336598036),
    .WIDTH(32'd5)
  ) _15_ (
    .A({ G13, G12, G11, G10, G0 }),
    .Y(n26)
  );
  \$lut  #(
    .LUT(16'b0001010101000000),
    .WIDTH(32'd4)
  ) _16_ (
    .A({ G12, G11, G10, G0 }),
    .Y(n31)
  );
  \$lut  #(
    .LUT(32'd357646336),
    .WIDTH(32'd5)
  ) _17_ (
    .A({ G13, G12, G11, G10, G0 }),
    .Y(n36)
  );
  \$lut  #(
    .LUT(64'b0000000001010101000101010100000000000000010101010101010100000000),
    .WIDTH(32'd6)
  ) _18_ (
    .A({ n57, G23, G14, G13, G10, G0 }),
    .Y(n41)
  );
  \$lut  #(
    .LUT(4'b0001),
    .WIDTH(32'd2)
  ) _19_ (
    .A({ G12, G11 }),
    .Y(n57)
  );
  \$lut  #(
    .LUT(4'b0001),
    .WIDTH(32'd2)
  ) _20_ (
    .A({ n59, G0 }),
    .Y(n46)
  );
  \$lut  #(
    .LUT(64'b0000000000000000111111111110111100000000001000001111111111111111),
    .WIDTH(32'd6)
  ) _21_ (
    .A({ G22, G15, G14, G13, G12, G11 }),
    .Y(n59)
  );
  \$lut  #(
    .LUT(32'd3960209408),
    .WIDTH(32'd5)
  ) _22_ (
    .A({ n59, G16, G14, G13, G12 }),
    .Y(n51)
  );
  \$lut  #(
    .LUT(64'b1111111000000111000000100000011100000000000000000000000000000000),
    .WIDTH(32'd6)
  ) _23_ (
    .A({ n59, G17, G14, G13, G12, G11 }),
    .Y(n56)
  );
  \$lut  #(
    .LUT(64'b1111111000001111000000100000111100000000000000000000000000000000),
    .WIDTH(32'd6)
  ) _24_ (
    .A({ n59, G18, G14, G13, G12, G11 }),
    .Y(n61)
  );
  \$lut  #(
    .LUT(8'b11010001),
    .WIDTH(32'd3)
  ) _25_ (
    .A({ n64, n59, G10 }),
    .Y(n66_1)
  );
  \$lut  #(
    .LUT(32'd4260364784),
    .WIDTH(32'd5)
  ) _26_ (
    .A({ G19, G14, G13, G12, G11 }),
    .Y(n64)
  );
  \$lut  #(
    .LUT(64'b1111111100000011010101010101010100000000000000000101010101010101),
    .WIDTH(32'd6)
  ) _27_ (
    .A({ n66, n59, G20, G13, G12, G10 }),
    .Y(n71)
  );
/*  \$lut  #(	// Copy of generated fpga lut order
    .LUT(64'b1000100010001000101110001011101110001000100010001000100010111011),
    .WIDTH(32'd6)
  ) _27_ (
    .A({ G10, n59, G13, G20, n66, G12 }),
    .Y(n71)
  ); */
  \$lut  #(
    .LUT(16'b1111110100000000),
    .WIDTH(32'd4)
  ) _28_ (
    .A({ G14, G13, G12, G11 }),
    .Y(n66)
  );
  \$lut  #(
    .LUT(64'b1111110000001000000000000000100000000000000000000000000000000000),
    .WIDTH(32'd6)
  ) _29_ (
    .A({ n59, G21, G14, G13, G12, G11 }),
    .Y(n76)
  );
  \$lut  #(
    .LUT(8'b00010100),
    .WIDTH(32'd3)
  ) _30_ (
    .A({ G22, G2, G0 }),
    .Y(n81)
  );
  \$lut  #(
    .LUT(8'b00010100),
    .WIDTH(32'd3)
  ) _31_ (
    .A({ G23, G1, G0 }),
    .Y(n86)
  );
  assign G67 = G17;
  assign G133 = G21;
  assign G118 = G19;
  assign G66 = G16;
  assign G132 = G20;
  assign G117 = G18;
endmodule
