#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "util.h"
#include "mpack_types.h"
#include "mpack_conf.h"
#include "blearch_parser.h"
#include "mpack_util.h"

/* Print out MPACK output blif
 * Key updates: use keyword "unconn" for those un-used BLE outputs and inputs
 */
int print_blif(char* output_blif_name,
               t_lgkntwk* lgkntwk,
               t_ble_arch* ble_arch,
               t_ble_info* ble_info,
               char* model_name,
               int verbose)
{
  t_ble_info* head = ble_info->next;
  FILE* fp;
  int line_cnt = 0;
  int char_cnt = 0;
  int char_thres = 5;
  int tmp;
  int im,ip;
  t_lgknd* cur;
  
  /*Open the output blif file*/
  printf("Print output Blif(%s) after MPACK...\n",output_blif_name);
  fp  = my_fopen(output_blif_name,"w");

  /*Print model name*/
  fputs("#Blif Netlist Generated by Mpack " __DATE__,fp);
  line_cnt++;
  fprintf(fp,"\n.model %s\n",model_name);
  line_cnt++;
  /*Print inputs*/
  fprintf(fp,".inputs ");
  char_cnt = 1;
  if (0 < lgkntwk->latch_num) {
    fprintf(fp,"clk ");
  }
  for (im=0; im<lgkntwk->pi_num; im++) {
    fprintf(fp,"%s ",lgkntwk->pi_ptrs[im]->net_name);
    char_cnt++;
    if (char_thres == char_cnt) {
      fprintf(fp,"\\\n");
      char_cnt = 0;
    } 
  }
  fprintf(fp,"\n");
  line_cnt++;

  /*Print outputs*/
  fprintf(fp,".outputs ");
  char_cnt = 1;
  for (im=0; im<lgkntwk->po_num; im++) {
    fprintf(fp,"%s ",lgkntwk->po_ptrs[im]->net_name);
    char_cnt++;
    if (char_thres == char_cnt) {
      fprintf(fp,"\\\n");
      char_cnt = 0;
    } 
  }
  fprintf(fp,"\n");
  line_cnt++;
  fprintf(fp,"\n");
  line_cnt++;

  /*Print output buffers*/
  for (im=0; im<lgkntwk->po_num; im++) {
    cur = lgkntwk->po_ptrs[im];
    if (0 != strcmp(cur->inputs[0]->net_name,cur->net_name)) {
      fprintf(fp,".names %s %s\n",cur->inputs[0]->net_name,cur->net_name);
      fprintf(fp,"1 1\n");
      line_cnt += 2;
    }
  }
  fprintf(fp,"\n");
  line_cnt++;

  for (im=0; im<lgkntwk->latch_num; im++) {
    cur = lgkntwk->latch_ptrs[im];
    head= (t_ble_info*)cur->ble_info; 
    fprintf(fp,".latch %s ",cur->inputs[0]->net_name);
    fprintf(fp,"%s ",cur->net_name);
    fprintf(fp,"re clk %d #latch index:%d\n",cur->init_val,cur->idx);
    line_cnt++;
  } 
  fprintf(fp,"\n");
  line_cnt++;

  head = ble_info->next;
  /*Print Sub circuits*/
  while(head) {
    for (im = 0; im<head->blend_num; im++) {
      if (NULL != head->blend_lgknds[im]) {
        /*Print Cell name*/
        fprintf(fp,".subckt cell%d ",im);
        for (ip = 0; ip<ble_arch->blends[im].input_num; ip++) {
          if (0 == head->blend_port_used[im][ip]) {
            fprintf(fp,"I[%d]=unconn ",ip);
          }
          else {
            if (BLE_ND == ble_arch->blends[im].inputs[ip].cands[head->blend_muxes[im][ip]]->type) {
              cur = head->blend_lgknds[ble_arch->blends[im].inputs[ip].cands[head->blend_muxes[im][ip]]->blend_idx];
            }
            else if (BLE_IN == ble_arch->blends[im].inputs[ip].cands[head->blend_muxes[im][ip]]->type) {
              tmp = ble_arch->blends[im].inputs[ip].cands[head->blend_muxes[im][ip]]->idx;
              cur = head->input_lgknds[tmp]->inputs[head->input_lgknds_input_idx[tmp]];
            }
            else if (BLE_OUT == ble_arch->blends[im].inputs[ip].cands[head->blend_muxes[im][ip]]->type) {
              cur = head->output_lgknds[ble_arch->blends[im].inputs[ip].cands[head->blend_muxes[im][ip]]->idx];
            }
            else {
              printf("Error:(print_blif)Invalid Type of BLE port!\n");
              exit(1);
            }
            fprintf(fp,"I[%d]=%s ",ip,cur->net_name);
          }
        }
        fprintf(fp,"O[0]=%s #BLE index: %d lgknd index: %d\n",head->blend_lgknds[im]->net_name,head->idx,head->blend_lgknds[im]->idx);
        line_cnt++;
      }
    }
    /*NEXT Pointer*/
    head = head->next;
  } 
  fprintf(fp,".end\n");
  line_cnt++;

  /*Print subcircuit declaration*/
  for (im = 0; im<ble_arch->blend_num; im++) {
    fprintf(fp,"\n\n.model cell%d\n",im);
    line_cnt += 3;

    /*Print subckts inputs*/
    fprintf(fp,".inputs ");
    for (ip =0; ip<ble_arch->blends[im].input_num; ip++) {
      fprintf(fp,"I[%d] ",ip);
    }
    fprintf(fp,"\n");
    line_cnt++;

    /*Print subckts outputs*/
    fprintf(fp,".outputs ");
    fprintf(fp,"O[0]\n");
    line_cnt++;
  
    fprintf(fp,".blackbox\n");
    line_cnt++;

    fprintf(fp,".end\n");
    line_cnt++;
  }

  fprintf(fp,"\n");
  line_cnt++;
    
  fclose(fp); 

  printf("Print output Blif(%s,lines:%d) complete!\n",output_blif_name,line_cnt);

  return 1;
}  
               
