% Tree-like structure 
rram_mux_improv_2n1r_tree_0p5V = [ % size, #. of fins, delay, leakage, dynamic_power, energy_per_toggle
% input size = 2
% input size = 4
% input size = 6
% input size = 8
% input size = 10
% input size = 12
% input size = 14
% input size = 16
% input size = 18
% input size = 20
% input size = 22
% input size = 24
% input size = 26
% input size = 28
% input size = 30
% input size = 32
% input size = 34
% input size = 36
% input size = 38
% input size = 40
% input size = 42
% input size = 44
% input size = 46
% input size = 48
% input size = 50
];

rram_mux_improv_2n1r_tree_0p6V = [ % size, #. of fins, delay, leakage, dynamic_power, energy_per_toggle
% input size = 2
% input size = 4
% input size = 6
% input size = 8
% input size = 10
% input size = 12
% input size = 14
% input size = 16
% input size = 18
% input size = 20
% input size = 22
% input size = 24
% input size = 26
% input size = 28
% input size = 30
% input size = 32
% input size = 34
% input size = 36
% input size = 38
% input size = 40
% input size = 42
% input size = 44
% input size = 46
% input size = 48
% input size = 50
];

rram_mux_improv_2n1r_tree_0p7V = [ % size, #. of fins, delay, leakage, dynamic_power, energy_per_toggle
% input size = 2
% input size = 4
% input size = 6
% input size = 8
% input size = 10
% input size = 12
% input size = 14
% input size = 16
% input size = 18
% input size = 20
% input size = 22
% input size = 24
% input size = 26
% input size = 28
% input size = 30
% input size = 32
% input size = 34
% input size = 36
% input size = 38
% input size = 40
% input size = 42
% input size = 44
% input size = 46
% input size = 48
% input size = 50
];
