# Near VT FPGA
cd ./scripts
perl fpga_flow.pl -conf ../configs/ptm22nmhp_fpga_conf/K6_N10_I33_frac_ptm22nmhp_1p2V.conf -benchmark ../benchmarks/mcnc_big20.txt -rpt ../csv_rpts/K6_N10_I33_frac_ptm22nmhp_1p2V.csv -N 10 -K 6 -power -remove_designs -multi_thread 5 -vpr_fpga_spice ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_1p2V #-vpr_fpga_spice_leakage_only
perl fpga_flow.pl -conf ../configs/ptm22nmhp_fpga_conf/K6_N10_I33_frac_ptm22nmhp_1p0V.conf -benchmark ../benchmarks/mcnc_big20.txt -rpt ../csv_rpts/K6_N10_I33_frac_ptm22nmhp_1p0V.csv -N 10 -K 6 -power -remove_designs -multi_thread 5 -vpr_fpga_spice ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_1p0V #-vpr_fpga_spice_leakage_only
perl fpga_flow.pl -conf ../configs/ptm22nmhp_fpga_conf/K6_N10_I33_frac_ptm22nmhp_1p0V_rram.conf -benchmark ../benchmarks/mcnc_big20.txt -rpt ../csv_rpts/K6_N10_I33_frac_ptm22nmhp_1p0V_rram.csv -N 10 -K 6 -power -remove_designs -multi_thread 5 -vpr_fpga_spice ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_1p0V_rram #-vpr_fpga_spice_leakage_only
perl fpga_flow.pl -conf ../configs/ptm22nmhp_fpga_conf/K6_N10_I33_frac_ptm22nmhp_1p0V_rram_sized.conf -benchmark ../benchmarks/mcnc_big20.txt -rpt ../csv_rpts/K6_N10_I33_frac_ptm22nmhp_1p0V_rram_sized.csv -N 10 -K 6 -power -remove_designs -multi_thread 5 -vpr_fpga_spice ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_1p0V_rram_sized #-vpr_fpga_spice_leakage_only
#perl fpga_flow.pl -conf ../configs/ptm22nmhp_fpga_conf/K6_N10_I33_frac_ptm22nmhp_1p0V_rram_enhance.conf -benchmark ../benchmarks/mcnc_big20.txt -rpt ../csv_rpts/K6_N10_I33_frac_ptm22nmhp_1p0V_rram_enhance.csv -N 10 -K 6 -power -remove_designs -multi_thread 5 -vpr_fpga_spice ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_0p6V_rram_enhance #-vpr_fpga_spice_leakage_only
#perl run_fpga_spice.pl -conf ../vpr_fpga_spice_conf/sample.conf -task ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_0p8V_standard.txt -rpt ../vpr_fpga_spice_csv_rpts/K6_N10_I33_frac_ptm22nmhp_0p8V_standard_spice.csv -multi_thread 2 #-sim_leakage_power_only -parse_mux_testbench
#perl run_fpga_spice.pl -conf ../vpr_fpga_spice_conf/sample.conf -task ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_0p6V_standard.txt -rpt ../vpr_fpga_spice_csv_rpts/K6_N10_I33_frac_ptm22nmhp_0p6V_standard_spice.csv -multi_thread 2 #-parse_mux_testbench -sim_leakage_power_only
#perl run_fpga_spice.pl -conf ../vpr_fpga_spice_conf/sample.conf -task ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_0p6V_rram_standard.txt -rpt ../vpr_fpga_spice_csv_rpts/K6_N10_I33_frac_ptm22nmhp_0p6V_rram_standard_spice.csv -multi_thread 2 #-parse_mux_testbench -sim_leakage_power_only
#perl run_fpga_spice.pl -conf ../vpr_fpga_spice_conf/sample.conf -task ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_0p6V_rram_sized_standard.txt -rpt ../vpr_fpga_spice_csv_rpts/K6_N10_I33_frac_ptm22nmhp_0p6V_rram_sized_standard_spice.csv -multi_thread 2 #-parse_mux_testbench -sim_leakage_power_only
#perl run_fpga_spice.pl -conf ../vpr_fpga_spice_conf/sample.conf -task ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_0p6V_rram_enhance_standard.txt -rpt ../vpr_fpga_spice_csv_rpts/K6_N10_I33_frac_ptm22nmhp_0p6V_rram_enhance_standard_spice.csv -multi_thread 2 #-parse_mux_testbench -sim_leakage_power_only
cd ..
