# Near VT FPGA
cd ./scripts
#perl fpga_flow.pl -conf ../configs/ptm22nmhp_fpga_conf/K6_N10_I33_frac_ptm22nmhp_0p8V.conf -benchmark ../benchmarks/mcnc_big20.txt -rpt ../csv_rpts/K6_N10_I33_frac_ptm22nmhp_0p8V.csv -N 10 -K 6 -power -remove_designs -multi_thread 5 -vpr_fpga_spice ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_0p8V #-vpr_fpga_spice_leakage_only
#perl fpga_flow.pl -conf ../configs/K6_N10_I33_frac_UMC180nm_1p2V.conf -benchmark ../benchmarks/mcnc_big20.txt -rpt ../csv_rpts/K6_N10_I33_frac_UMC180nm_1p2V.csv -N 10 -K 6 -power -remove_designs -multi_thread 5 -vpr_fpga_spice ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_UMC180nm_1p2V -vpr_fpga_spice_leakage_only
#perl fpga_flow.pl -conf ../configs/K6_N10_I33_frac_UMC180nm_1p2V_rram.conf -benchmark ../benchmarks/mcnc_big20.txt -rpt ../csv_rpts/K6_N10_I33_frac_UMC180nm_1p2V_rram.csv -N 10 -K 6 -power -remove_designs -multi_thread 5 -vpr_fpga_spice ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_UMC180nm_1p2V_rram -vpr_fpga_spice_leakage_only
#perl fpga_flow.pl -conf ../configs/K6_N10_I33_frac_UMC180nm_1p2V_rram_sizing.conf -benchmark ../benchmarks/mcnc_big20.txt -rpt ../csv_rpts/K6_N10_I33_frac_UMC180nm_1p2V_rram_sizing.csv -N 10 -K 6 -power -remove_designs -multi_thread 5 -vpr_fpga_spice ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_UMC180nm_1p2V_rram_sizing -vpr_fpga_spice_leakage_only
perl run_fpga_spice.pl -conf ../vpr_fpga_spice_conf/sample.conf -task ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_ptm22nmhp_0p8V_standard.txt -rpt ../vpr_fpga_spice_csv_rpts/K6_N10_I33_frac_ptm22nmhp_0p8V_standard_spice.csv -multi_thread 2 -sim_leakage_power_only #-parse_mux_testbench
#perl run_fpga_spice.pl -conf ../vpr_fpga_spice_conf/sample.conf -task ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_UMC180nm_1p2V_standard.txt -rpt ../vpr_fpga_spice_csv_rpts/K6_N10_I33_frac_UMC180nm_1p2V_standard_spice.csv -parse_mux_testbench -multi_thread 2 -sim_leakage_power_only
#perl run_fpga_spice.pl -conf ../vpr_fpga_spice_conf/sample.conf -task ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_UMC180nm_1p2V_rram_standard.txt -rpt ../vpr_fpga_spice_csv_rpts/K6_N10_I33_frac_UMC180nm_1p2V_rram_standard_spice.csv -parse_mux_testbench -multi_thread 2 -sim_leakage_power_only
#perl run_fpga_spice.pl -conf ../vpr_fpga_spice_conf/sample.conf -task ../vpr_fpga_spice_task_lists/K6_N10_I33_frac_UMC180nm_1p2V_rram_sizing_standard.txt -rpt ../vpr_fpga_spice_csv_rpts/K6_N10_I33_frac_UMC180nm_1p2V_rram_sizing_standard_spice.csv -parse_mux_testbench -multi_thread 2 -sim_leakage_power_only
cd ..
